export const colors ={
    BUTTON_SIGNIN : "#A25426",
    BUTTON_SIGNUP : "#323232",
    FONT_WHITE: "#FFFFFF",
    SEPARATED_LINE : "#E5E5E5",
    SEPARATED_LINE_TORNUP : "#515151",
    BACKGROUND_DEFAULT : "#FEFCFC",
    BACKGROUND_LIGHTGRAY : "#F2F4F6",
    BACKGROUND_WHITE_DOWN : "#FAFAFA",
    REFRIGATOR_AI_BUTTON:"#cb6930",
    SELECTED_ITEM_BACKGROUND : "#ffcc99",
    ITEM_ARROW_GRAY : "#CDCDCD",
    ITEM_BORDER_GRAY : "#636363",

    RECIPENM_INPUT: '#B98639',
    IMAGE_PAGE_ORANGE : "#FF8E4C",
    KCAL_INPUT_BOX:"#9E8C70",

    DEFAULT_IOS_BACKGROUND: "#EFEFEF",
    
    LANDING_BACK_COLOR : "#FF9C27",
    LANDING_SIGNUP_BLACK:"#303030",
    LANDING_SIGNUP_BLACK_HOVER:"#404040"


}